apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    app: users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: docker.io/anikolaevdo/users
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: users-env
                  key: DB_HOST
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: users-env
                  key: DB_NAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: users-env
                  key: DB_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    app: users
spec:
  type: ClusterIP
  selector:
    app: users
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
